### ISSUE TITLE
run_list json objects returns caste_rule hash references

### ISSUE THREAD

**Issue by dnbert** [edolnx/nephology-server-perl#20]
During install, nephology-client fails due to caste_rule id's being returned as hash references. These objects should be either a.) dereferenced on the server side or b.) not be hashed at all. Here's an example:

```
brettg@odin:~$ lynx 50.19.218.14:3000/install/60:eb:69:ed:9f:00
```

Which returns:

```
brettg@odin:~$ vim 60\:eb\:69\:ed\:9f\:00 
```

And this is the contents inside:

```
1 {"runlist":       ["CasteRule=HASH(0x437dcb8)","CasteRule=HASH(0x4410aa8)","CasteRule=HASH(0x4367658)","CasteRule=HASH(0x436d8f8)"],"version_required":2}
```

This should probably be served as a straight json blob or not nested hashes maybe? 

Here's a sample from the client:

```
hash- or arrayref expected (not a simple scalar, use allow_nonref to allow this) at ./neph-client.pl line 57
```

Which refers to this:

```
 56     for my $reqhash (@{$nephology_commands->{'runlist'}}) {
 57         print "Got command: " . JSON->new->utf8->encode($reqhash) . "\n";
 58     }
```

**Comment by Thingee** [comment]
https://github.com/edolnx/nephology-server-perl/pull/21
